import express from 'express'; import jwt from 'jsonwebtoken'; import User from '../models/User.js'; import { isMongoConnected } from '../config/db.js'; import { createUser, findUserByEmail, matchPassword, updateUserPassword } from '../data/jsonDb.js';
const router = express.Router();
const jwtSecret = process.env.JWT_SECRET || 'zentra-dev-secret';
const tokenFor = (user) => jwt.sign({ id: user._id }, jwtSecret, { expiresIn: '7d' });
const sendUser = (res, user, status = 200) => res.status(status).json({ token: tokenFor(user), user: { _id: user._id, name: user.name, email: user.email, role: user.role } });
router.post('/register', async (req, res, next) => { try { const { name, email, password } = req.body; if (!name || !email || !password) return res.status(400).json({ message: 'Name, email and password are required.' }); if (isMongoConnected()) { if (await User.findOne({ email })) return res.status(409).json({ message: 'An account with this email already exists.' }); return sendUser(res, await User.create({ name, email, password }), 201); } if (await findUserByEmail(email)) return res.status(409).json({ message: 'An account with this email already exists.' }); sendUser(res, await createUser({ name, email, password }), 201); } catch (e) { next(e); } });
router.post('/login', async (req, res, next) => { try { if (isMongoConnected()) { const user = await User.findOne({ email: req.body.email?.toLowerCase() }); if (!user || !(await user.matchPassword(req.body.password))) return res.status(401).json({ message: 'Incorrect email or password.' }); return sendUser(res, user); } const user = await findUserByEmail(req.body.email); if (!user || !(await matchPassword(user, req.body.password))) return res.status(401).json({ message: 'Incorrect email or password.' }); sendUser(res, user); } catch (e) { next(e); } });
router.post('/forgot-password', async (req, res, next) => { try { const { email, password } = req.body; if (!email || !password) return res.status(400).json({ message: 'Email and new password are required.' }); if (password.length < 6) return res.status(400).json({ message: 'New password must be at least 6 characters.' }); if (isMongoConnected()) { const user = await User.findOne({ email: email.toLowerCase() }); if (!user) return res.status(404).json({ message: 'No account found with this email.' }); user.password = password; await user.save(); return res.json({ message: 'Password updated successfully' }); } const user = await updateUserPassword(email, password); if (!user) return res.status(404).json({ message: 'No account found with this email.' }); res.json({ message: 'Password updated successfully' }); } catch (e) { next(e); } });
export default router;
