import express from 'express'; import Product from '../models/Product.js'; import { protect, admin } from '../middleware/auth.js'; import { isMongoConnected } from '../config/db.js'; import { createProduct, deleteProduct, getCategories, getProductById, getProducts, updateProduct } from '../data/jsonDb.js';
const router = express.Router();
router.get('/', async (req, res, next) => { try { if (!isMongoConnected()) return res.json(await getProducts(req.query)); const filter = {}; if (req.query.category && req.query.category !== 'All') filter.category = req.query.category; if (req.query.search) filter.$or = ['title', 'description'].map(k => ({ [k]: { $regex: req.query.search, $options: 'i' } })); res.json(await Product.find(filter).sort({ featured: -1, createdAt: -1 })); } catch(e) { next(e); } });
router.get('/categories', async (req,res,next) => { try { res.json(isMongoConnected() ? await Product.distinct('category') : await getCategories()); } catch(e) { next(e); } });
router.get('/:id', async (req,res,next) => { try { const product = isMongoConnected() ? await Product.findById(req.params.id) : await getProductById(req.params.id); if (!product) return res.status(404).json({ message: 'Product not found.' }); res.json(product); } catch(e) { next(e); } });
router.post('/', protect, admin, async (req,res,next) => { try { res.status(201).json(isMongoConnected() ? await Product.create(req.body) : await createProduct(req.body)); } catch(e) { next(e); } });
router.put('/:id', protect, admin, async (req,res,next) => { try { const item = isMongoConnected() ? await Product.findByIdAndUpdate(req.params.id, req.body, { new:true, runValidators:true }) : await updateProduct(req.params.id, req.body); if (!item) return res.status(404).json({message:'Product not found.'}); res.json(item); } catch(e) { next(e); } });
router.delete('/:id', protect, admin, async (req,res,next) => { try { const item = isMongoConnected() ? await Product.findByIdAndDelete(req.params.id) : await deleteProduct(req.params.id); if (!item) return res.status(404).json({message:'Product not found.'}); res.json({message:'Product deleted.'}); } catch(e) { next(e); } });
export default router;
